name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download PlantUML
        run: wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Generate diagrams
        run: |
          mkdir -p images
          java -jar plantuml.jar *.puml -o images/

      - name: Commit and push generated images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add only if there are changes
          git add images/*
          git diff --quiet && git diff --staged --quiet || git commit -m "Update generated diagrams" && git push